In [14]:
## sudo apt update
##sudo apt install python3-venv
#python3 -m venv venv
#source venv/bin/activate

##pip install numpy

# This command to used to active the numpy envirounment


In [15]:
##Numpy arrray and basics learn about with nympy

In [16]:
import numpy as np ##use kar ke liya ham import kar te hai

In [17]:
##Creating array from list
arr_Id = np.array([1,2,3,4,5])
print(arr_Id)

arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

arr_3d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr_3d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [18]:
##List Vs numpy array

py_list = [1,2,3,4,5]
print("Print list multiplication", py_list*2)## python ka array me hamko ye array ka multiplication karenge dounbra lika dega

np_arr = np.array([1,2,3,4,5])
print("Print numpy array multiplication", np_arr*2)##numpy ka array me ye array ko sabko ek ek kar ke array ke element ko multiply karega

import time
start = time.time()
py_list = [i*2 for i in range(100000)]
print("\n List operation time", time.time() - start)## ye hamko dono operation ka time print karega

start = time.time()
np_array = np.arange(100000)*2
print("\n Numpy array operation time", time.time() - start)





Print list multiplication [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Print numpy array multiplication [ 2  4  6  8 10]

 List operation time 0.01984429359436035

 Numpy array operation time 0.0011680126190185547


In [28]:
##Creating array from Scrath

zeros = np.zeros((3,4))## 3 yaha par row and 4 yaha par column
print("Zeros array:\n",zeros) ## ye hamko 3 rows aur 4 column ka array print karega jisme sab element 0 honge because ham zero method ka use kar rahi hai

ones = np.ones((2,3))##isme sab ka value 1 honge element ka
print("ones\n", ones)

empty = np.empty((3,3))
print(empty)


full = np.full((2,2), 7)## ye bhi same hi hai bass ek spacial shape deta hai
print("full array:\n", full)

eye = np.eye(5)## eye methods hamko diagonal hamko ye left side 1 print kar ke dega
print("eye array:\n", eye)

random = np.random.random((2,3))# ye hamko 2 row and 3 column ka random array print karega
print("random array:\n", random)

sequence = np.arange(0, 10, 2) ## (start, stop, step) kaega ye 
print("sequence array:\n", sequence)

linspace = np.linspace(0, 10, 5)
print("linspace array:\n", linspace)




Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones
 [[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
full array:
 [[7 7]
 [7 7]]
eye array:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
random array:
 [[0.71006522 0.11667855 0.54429929]
 [0.91682985 0.20143894 0.14577813]]
sequence array:
 [0 2 4 6 8]
linspace array:
 [ 0.   2.5  5.   7.5 10. ]


In [29]:
##Vector,Matrix, Tensor

vector = np.array([1,2,3])
print("vector:\n", vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("matrix:\n", matrix)

tensor = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print("tensor:\n", tensor)

vector:
 [1 2 3]
matrix:
 [[1 2 3]
 [4 5 6]]
tensor:
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [37]:
#Array Properties

arr = np.array([1,2,3,4,5])
print("Shape", arr.shape)
print("Size", arr.size)
print("Type", arr.dtype)
print("Item size", arr.itemsize)
print("Total bytes", arr.nbytes)
print("Data type", arr.dtype)



Shape (5,)
Size 5
Type int64
Item size 8
Total bytes 40
Data type int64


In [ ]:
##Array Reshaping

arr = np.arange(12)
print("Original array:\n", arr)
print("Reshaped array:\n", arr.reshape(3,4))## range diya huwa hai jo matrix ko resape karge 3,4 ke order me
print("Flatten array:\n", arr.flatten())

raveled = arr.ravel()
print("Raveled array:\n", raveled)

## Transpose

arr = np.array([[1,2,3],[4,5,6]])# change the element in a matrix to row to column && column to row
print("Original array:\n", arr)
print("Transpose array:\n", arr.T)



Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatten array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Original array:
 [[1 2 3]
 [4 5 6]]
Transpose array:
 [[1 4]
 [2 5]
 [3 6]]
