In [10]:
##Numpy Array operations'
import numpy as np
import time

In [11]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing", arr[0:5])## ye hamko 0 number se slicing kar ke hamko ye indexing 4 tak ka position ka element dega nikal kar
print("with step", arr[0:10:2])##ye hamko 0 se start kar ke 10 indexing number tak se ye 2 elemnt ka gap kar dega
print("Negative indexing", arr[-1]) ## ye hamko array ke last postion ka value dega
print("Negative indexing", arr[-2]) ## ye hamko array ke last postion ka value dega

Basic Slicing [1 2 3 4 5]
with step [1 3 5 7 9]
Negative indexing 10
Negative indexing 9


In [12]:
arr_2d = np.array([[1,2,3],##1 row ka indexing 0
                   [4,5,6],##2 row ka indexing 1
                   [7,8,9],])##3 row ka indexing 2

print("Sepcfic element", arr_2d[1,2]) ## ye hamko 1 row ka 2 indexing ka element dega
print("Sepcfic element", arr_2d[2,1]) ## ye hamko 2 row ka 1 indexing ka element dega
print("Sepcfic element", arr_2d[0,0]) ## ye hamko 0 row ka 0 indexing ka element dega

print("Whole elements of 1 row/n", arr_2d[1]) ## ye hamko 1 row ham yayah par indexing me ham [1] pass kar rahi hai to ye hamko pura element dega 

print("Whole elements of Column 2 row/n", arr_2d[:,1]) ## ye hamko 2 row ham yayah par indexing me ham [2] pass kar rahi hai to ye hamko pura element dega
## iska matlab hai ki ham  first row ka second column ka element ko full target kar rahi hai

Sepcfic element 6
Sepcfic element 8
Sepcfic element 1
Whole elements of 1 row/n [4 5 6]
Whole elements of Column 2 row/n [2 5 8]


In [16]:
##Sorting
unsorted = np.array([5,2,3,1,4])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1], [1,2], [2,3]])
print("Sorting 2D array by Column",np.sort(arr_2d_unsorted, axis=0))

Sorted Array [1 2 3 4 5]
Sorting 2D array by Column [[1 1]
 [2 2]
 [3 3]]


In [ ]:
##Filter

numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]# condation of even number
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


In [19]:
##Filter with Mask

mask = numbers > 5
print("Filter with mask", numbers[mask])##ye number ko increase karge

Filter with mask [ 6  7  8  9 10]


In [21]:
##Fancy indexing vs np.where()

indices = [0,2,4]
print(numbers[indices])##ye hamko fancy indexing ka use kar rahi hai

where_result = np.where(numbers > 5)
print("Where result", numbers[where_result])##ye hamko np.where ka use kar rahi hai


[1 3 5]
Where result [ 6  7  8  9 10]


In [27]:
condition_array = np.where(numbers > 5, "true","false" )
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


In [ ]:
###Adding and removing data

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

combined = np.concatenate((arr1,arr2))## ya wala method hamko dono arry ko combinre kar  ke dega
print("Combined array", combined)

removed = np.delete(combined, 2)
print("Removed array", removed)## arraty ko removed kae dega array me se


Combined array [ 1  2  3  4  5  6  7  8  9 10]
Removed array [ 1  2  4  5  6  7  8  9 10]


In [36]:
##array Compatibilty

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print("Array shapes", a.shape ==  b.shape, c.shape)


Array shapes True (3,)


In [45]:
original = np.array([[1,2,3], [3,4,5]])
new_row = np.array([[5,6,7]])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print(original)
print(with_new_col)


[[1 2 3]
 [3 4 5]]
[[1 2 3]
 [3 4 5]
 [5 6 7]]
[[1 2 3]
 [3 4 5]]
[[1 2 3 7]
 [3 4 5 8]]


In [ ]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)
print(deleted)


[1 2 4 5]
